source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'DiveAdvisor' do
    pod 'Alamofire', '~> 4.4'
    pod 'Kingfisher', '~> 3.5'
    pod 'SVProgressHUD', '~> 2.1'

end
